[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
veralux = "B7ey9pqVRrtFWDWLWuDr9VxD1VWdn1YviVg74vw4cPwq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./keypairs/main.json"
