[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
veralux = "xikFFfUa48SD9UZcHjRmkaSKuso7WXQXyxRP4t5EEZY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./key.json"
