[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
veralux = "FVrTj1gzeyFBMnQsMXTQUYvtXqU8m6cJtdk3VFeSfHf1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./key.json"
